### ISSUE TITLE
Broken operation with pillow version 7.0

### ISSUE THREAD

**Issue by pp-mo** [SciTools/test-iris-imagehash#28]
Discovered in course of [Iris#3628](https://github.com/SciTools/iris/pull/3628) that Iris graphics tests have just broken.

After some investigation, determined that this is due to changed results from key pillow (aka PIL) operations that `imagehash.phash()` relies on, since pillow v7.0.0 came out.
  * the whole usage of iris graphics tests (`IrisTest.check_graphic`), the `iris/tests/idiff.py` command, and this repo currently **relies on** the idea that an image produces a unique stable hash value, determined by 'imagehash.phash(image)', and we use that hash value (in hex ) as the name for the image file stored in test-iris-imagehash
  * the hashes of all our stored image files _have_ in fact remained stable since we first developed test-iris-imagehash.
    * E.G. at [this old commit, dated 2018-4-11](https://github.com/SciTools/test-iris-imagehash/commit/fb3b96b902c7e9d6f7ce95f5d59ce6d243567c7f), the Travis log shows we were initially operating with pillow version 3.2.1
    * .. whereas in this [most recent successful commit, 2019-10-16]() we were still getting the same values, with pillow version 6.2.0
    * **but this has now failed**  with pillow v7.0.0 : some stored images are now producing different hashes
  * this relationship is tested by [test-iris-imagehash/run_test.py](https://github.com/SciTools/test-iris-imagehash/blob/005440e27e4756b3aa326f54b00d622faf45d595/run_test.py) : It checks that all the files compute a hash equal to their filename.  Until fixed, ***this will break all PR tests from now on***

On reflection, fixing this is all a bit tricky :  There is no guarantee or expectation in [pillow (aka PIL)](https://github.com/python-pillow/Pillow) that the results of operations would be exactly the same between different package versions.  In fact, even [imagehash](https://github.com/JohannesBuchner/imagehash) itself does not make such a claim : it provides provide toleranced image compare by calculating hashes that can be differenced, but this does not mean that the hash values themselves are necessarily portable from one version to another.
We already had one such problem, where hash numbers changes in imagehash version 4, as fixed in #14.  Arguably, we have just been "lucky" since then (!)  More recently, [imagehash#32](https://github.com/JohannesBuchner/imagehash/issues/32) raises a similar problem with possible pillow changes (that presumably worked out ok).  

Temporarily fixed in Iris by pinning : https://github.com/SciTools/iris/pull/3630

----

A "proper" fix would involve changes both here and in Iris.  
One possible way ...
  * associate hashes with specific dependency versions (imagehash, pillow, possibly scipy?)
  * decouple storage filenames from the hash info (or possibly use softlinks as was done in #14)
  * make sure Iris only uses hashes appropriate to the current installed library(s) when calculating compare distances
This assumes we **need** to retain function with old versions of dependencies, and implies we must know hashes for all files at multiple versions.

Another way is only to support a latest version (fixed or pinned), and insist only that is useable.
This means when problems occur we would _rename all the image files, and change Iris imagerepo.json_.  Tests will then no longer work with older versions of pillow (+poss others).

**Comment by rcomer** [comment]
I guess we can close this, thanks to @wjbenfold in https://github.com/SciTools/iris/pull/4759 and https://github.com/SciTools/iris/pull/4826.
